# Generated by Django 4.2.8 on 2023-12-08 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Guide',
        ),
    ]
